config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :movimentations
  resources :sources
  devise_for :users
  get 'home/index'

  authenticated :user do
    root "movimentations#index", as: 'authenticated_root'
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :user
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: %i[ show edit update destroy ]

  # GET /sources or /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/1 or /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources or /sources.json
  def create
    @source = Source.new(source_params)
    @source.user = current_user

    respond_to do |format|
      if @source.save
        format.html { redirect_to source_url(@source), notice: "Source was successfully created." }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1 or /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to source_url(@source), notice: "Source was successfully updated." }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1 or /sources/1.json
  def destroy
    @source.destroy

    respond_to do |format|
      format.html { redirect_to sources_url, notice: "Source was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def source_params
      params.require(:source).permit(:name)
    end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_form.html.erb
<%= form_with(model: source) do |form| %>
  <% if source.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
        <% source.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sources/_source.html.erb
<div id="<%= dom_id source %>">
  <p>
    <strong>Name:</strong>
    <%= source.name %>
  </p>
  <p>
    <strong>user:</strong>
    <%= source.user.email %>
  </p>

</div>

app/views/sources/edit.html.erb
<h1>Editing source</h1>

<%= render "form", source: @source %>

<br>

<div>
  <%= link_to "Show this source", @source %> |
  <%= link_to "Back to sources", sources_path %>
</div>

app/views/sources/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sources</h1>

<div id="sources">
  <% @sources.each do |source| %>
    <%= render source %>
    <p>
      <%= link_to "Show this source", source %>
    </p>
  <% end %>
</div>

<%= link_to "New source", new_source_path %>

app/views/sources/new.html.erb
<h1>New source</h1>

<%= render "form", source: @source %>

<br>

<div>
  <%= link_to "Back to sources", sources_path %>
</div>

app/views/sources/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @source %>

<div>
  <%= link_to "Edit this source", edit_source_path(@source) %> |
  <%= link_to "Back to sources", sources_path %>

  <%= button_to "Destroy this source", @source, method: :delete %>
</div>