config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :movimentations
  resources :sources
  devise_for :users
  get 'home/index'

  authenticated :user do
    root "movimentations#index", as: 'authenticated_root'
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/movimentation.rb
class Movimentation < ApplicationRecord
  belongs_to :user
  belongs_to :source

  has_one :category

  enum operation: {in: 0, out: 1}

  scope :filter_for_date, ->(search = Time.now) { where('date_transaction >= :start_date AND date_transaction <= :end_date',
    {:start_date => Time.new(search.year, search.month, search.day) - 3.hours, :end_date => Time.new(search.year, search.month, search.day, 20, 59)}) }

  scope :filter_atual_month_trasactions, -> { where('date_transaction BETWEEN ? AND ?', Date.today.beginning_of_month, Date.today.end_of_month) }

  scope :sum_value, -> { pluck(:value).sum }

  def total_in_month
    Transaction.where(operation: 'in').where('date_trasaction BETWEEN ? AND ?', Date.today.beginning_of_month, Date.today.end_of_month).pluck(:value).sum
  end
end

app/controllers/movimentations_controller.rb
class MovimentationsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @movimentations = get_current_trasactions.filter_for_date(search_date)
    if current_user.present?
      @sources = current_user.sources
      @total_in_month = get_current_trasactions.where(operation: 'in').filter_atual_month_trasactions.sum_value
      @total_out_month = get_current_trasactions.where(operation: 'out').filter_atual_month_trasactions.sum_value
    end
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @movimentation = Movimentation.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @movimentation = Movimentation.new(transaction_params)
    @movimentation.user = current_user

    respond_to do |format|
      if @movimentation.save
        format.html { redirect_to movimentation_url(@movimentation), notice: "movimentation was successfully created." }
        format.json { render :show, status: :created, location: @movimentation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movimentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @movimentation.update(transaction_params)
        format.html { redirect_to movimentation_url(@movimentation), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @movimentation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movimentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @movimentation.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @movimentation = Movimentation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:movimentation).permit(:operation, :description, :value, :user_id, :source_id, :date_transaction)
    end

    def get_current_trasactions
      current_user.movimentations
    end

    def search_date
      return DateTime.iso8601(params[:search]) if params[:search].present?
      Time.now
    end

    def sum_value
      pluck(:value).sum
    end
end

app/views/movimentations/_form.html.erb
<%= form_with(model: movimentation) do |form| %>
  <% if movimentation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movimentation.errors.count, "error") %> prohibited this movimentation from being saved:</h2>

      <ul>
        <% movimentation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :operation, style: "display: block" %>
    <%= form.select :operation, Movimentation.operations.keys %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.label :source_id, style: "display: block" %>
    <%= form.collection_select :source_id, current_user.sources ,:id,:name, include_blank: true %>
  </div>

  <div>
    <%= form.label :date_transaction, style: "display: block" %>
    <%= form.date_field :date_transaction, :value => Time.now.strftime('%Y-%m-%d') %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movimentations/_movimentation.html.erb
<div id="<%= dom_id movimentation %>">
  <p>
    <strong>Operation:</strong>
    <%= movimentation.operation %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= movimentation.description %>
  </p>

  <p>
    <strong>Value:</strong>
    R$ <%= movimentation.value %>
  </p>

  <p>
    <strong>User:</strong>
    <%= movimentation.user.email %>
  </p>

  <p>
    <strong>Source:</strong>
    <%= movimentation.source.name %>
  </p>

  <p>
    <strong>Date movimentation:</strong>
    <%= movimentation.date_transaction.strftime('%Y-%m-%d') %>
  </p>

</div>

app/views/movimentations/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", movimentation: @movimentation %>

<br>

<div>
  <%= link_to "Show this transaction", @movimentation %> |
  <%= link_to "Back to transactions", movimentation_path %>
</div>

app/views/movimentations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

<div id="transactions">
<%= form_tag root_path, :method => 'get' do %>
  <p>
    <%= date_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<% if @total_in_month.present? %>
  <h3>Total Mês ganho: R$ <%= @total_in_month%></h3>
<% end %>
<% if @total_out_month.present? %>
  <h3>Total Mês Gastos: R$ <%= @total_out_month%></h3>
<% end %>
  <% @sources.each do |source|%>
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th colspan="5" scope="col" style="text-align:center;"><%= source.name.capitalize %></th>
        <tr>
        <tr>
          <th scope="col">Operation</th>
          <th scope="col">Description</th>
          <th scope="col">Value</th>
          <th scope="col">Date</th>
          <th scope="col">Show</th>
        </tr>
     </thead>
     <% @movimentations.each do |transaction| %>
      <tbody> 
        <% if transaction.source == source%>
          <tr class=<%= transaction.operation == 'in' ? "table-success" : "table-danger" %>>
            <th scope="row"><%=transaction.operation %></th>
            <td><%=transaction.description %></td>
            <td>R$ <%= transaction.value %></td>
            <td><%= transaction.date_transaction.strftime('%d/%m/%Y') %></td>
            <td><%= link_to "Show this transaction", transaction %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
    </table>
  <% end %>
</div>

<%= link_to "New transaction", new_movimentation_path %>

app/views/movimentations/new.html.erb
<h1>New transaction</h1>

<%= render "form", movimentation: @movimentation %>

<br>

<div>
  <%= link_to "Back to transactions", movimentations_path %>
</div>

app/views/movimentations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movimentation %>

<div>
  <%= link_to "Edit this transaction", edit_movimentation_path(@movimentation) %> |
  <%= link_to "Back to transactions", movimentations_path %>

  <%= button_to "Destroy this transaction", @movimentation, method: :delete %>
</div>