config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :movimentations
  resources :sources
  devise_for :users
  get 'home/index'

  authenticated :user do
    root "movimentations#index", as: 'authenticated_root'
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :movimentation
  belongs_to :user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>
  <p>
    <strong>movimentation:</strong>
    <%= category.movimentation.description %>
  </p>
  <p>
    <strong>user:</strong>
    <%= category.user.email %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="sources">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New source", new_category_path %>